Added article refactoring
DXHeroes/knowledge-base-content pull request #316
Opened 2020-10-23 19:07 UTC by K-Kumar-01

Closes #261 

## If an article related PR

- [x] I have checked that my suggestion follows the Contribution guide

- [x]  I have added which issue this PR closes

- [ ] I have 0 warnings from Danger.js

- [x] If I have added images, they are in /files/ folder

## If other PR

- [ ] I have added which issue this PR closes

2020-10-29 06:36 UTC, prokopsimek requested changes
@K-Kumar-01 please see my suggestions. There could be more paragraphs but the article is fine.

cc @ridlees

2020-10-29 06:36 UTC, prokopsimek commented on practices/refactoring.md
> +short_description:In computer programming and software design, code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior.
```suggestion
short_description: In computer programming and software design, code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior.
```

2020-10-29 06:36 UTC, prokopsimek commented on practices/refactoring.md
> +  - production
```suggestion
  - development
```

`production` is not a valid stage - see Contribution guide for more info

2020-10-29 06:41 UTC, K-Kumar-01 commented
@prokopsimek  I have made the suggested changes.

2020-10-29 06:46 UTC, prokopsimek approved these changes

2020-11-04 21:30 UTC, ridlees requested changes
Hello @K-Kumar-01, sorry for my delay, I had some sick days. I like how on point and fresh your content is. Good job! Please, look at my suggestion and let me know if you find them valuable.

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +short_description: In computer programming and software design, code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior.
Please, rewrite this definition with your own words. Using the direct quote (even though is a good one) hurts this article.

_In computer programming and software design, code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior_ from https://en.wikipedia.org/wiki/Code_refactoring

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- [Agile Alliance](https://www.agilealliance.org/glossary/refactoring/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_pa
```suggestion
- [Agile Alliance](https://www.agilealliance.org/glossary/refactoring)
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +
I think you could also include this paper on the correlation between refactoring as practice and quality of code (10.1051/matecconf/20165702012) (if you don't have access to the academic sources, it is possible to use  https://scihub.wikicn.top to get the content. I am not encouraging you to use it).

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +1. Find the code which is used in many places.
```suggestion
1. Find the code which you use in many places.
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +3. Call that function in the place.
```suggestion
3. Call that function in the place instead.
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +4. Repeat till steps 1-3 cannot be done.
```suggestion
4. Repeat till you can not find frequently used code
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +**Some things to be taken care of **
```suggestion
**Keep in mind during refactoring**
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Refactoring the code makes it easier to understand for other people.
```suggestion
- Refactoring your code makes it easier to understand for other people.
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- It reduces the code which is less maintenance.
```suggestion
- It reduces code maintenance
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- It passes all the tests.
```suggestion
- It makes testing easier
```
I think that any piece of code should pass all the tests (not only refactored).

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Debugging and maintenance is easier.
```suggestion
- Debugging is easier.
```

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Improves the objective attributes of code(length, duplication, coupling ,etc.)
unfortunately, this sentence is too similar to _refactoring improves objective attributes of code (length, duplication, coupling, and cohesion_

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +
I would suggest mentioning something about a correct version control and refactoring. Something like when committing, use the label “Refactoring”. What do you think about this suggestion? Do you agree?

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +
```suggestion
- Helps to minimize [Poor Code Quality](/problems/poor-code-quality)
```
Some of the other problems could be included in this. What do you think about it?

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Expensive and risky in view of management.
```suggestion
- Expensive and risky in the view of management.
```
Or you could say Management can see refactoring as expensive and not important. Just suggestion

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Does not mean rewriting the code.
```suggestion
- Developer start adding new features, rewriting the code, or fixing bugs during refactoring.
```
I think these pitfalls can be grouped together.

2020-11-04 21:30 UTC, ridlees commented on practices/refactoring.md
> +- Challenging as small changes are not likely to be made because of laziness i.e. "Too small to worth doing".
```suggestion
- Lack of developer motivation to do these small changes
```

2020-12-08 16:08 UTC, ridlees approved these changes

2020-12-08 16:09 UTC, ridlees commented
Hello @K-Kumar-01, since it is a great article that I like a lot, I have taken the liberty to address all the comments. I am glad that we can publish it. Hurray 🎉 🎉 🎉

2020-12-08 16:09 UTC, merged