Test Cards
DXHeroes/knowledge-base-content pull request #372
Opened 2021-06-26 20:55 UTC by fanatiicx

Closes #154 

## If an article related PR

- [x] I have checked that my suggestion follows the Contribution guide

- [x]  I have added which issue this PR closes

- [x] I have 0 warnings from Danger.js

- [x] If I have added images, they are in /files/ folder

## If other PR

- [ ] I have added which issue this PR closes

2021-06-28 08:21 UTC, prokopsimek requested changes
@fanatiicx Thanks for the article! 👏

I have reviewed the article, proposed 2 suggestions that fix internal URLs, and added a keyword for SEO.

I am also not sure about those headlines. I'd suggest pluralizing all headlines and describe all sections as "test cards" instead of just singular "test card". E.g., `What Is a Test Card?` change to `What Are Test Cards?`. I need @ridlees opinion for this.

Also, the section `How to Implement...` is quite short, and I'd love to read more about the phase before the filling test card. What do I need to prepare before, and in what phase of a product are test cards valuable? When should I start testing with test cards, and how looks the process after the test card is filled? Should I start testing my hypothesis with people, or are these test cards just for our internal purposes?

Thanks, @fanatiicx! I welcome any other suggestions or discussions.

Please, @ridlees, could you also do a review? I am fine with the length of the article and just missing some more "sauce" there.

2021-06-28 08:21 UTC, prokopsimek commented on practices/test_cards.md
> +  - value proposition
```suggestion
  - test cards
  - value proposition
```

2021-06-28 08:21 UTC, prokopsimek commented on practices/test_cards.md
> +- [Unsuccessful Product](/problems/unsuccessful_products)
```suggestion
- [Bad Product-Market Fit](/problems/bad-product-market-fit)
- [Sunk Cost](/problems/sunk-cost)
- [Unhappy Clients](/problems/unhappy-clients)
- [Unnecessary Features](/problems/unnecessary-features)
- [Unsuccessful Product](/problems/unsuccessful-products)
```

2021-06-28 10:44 UTC, zeman-j4 approved these changes

2021-06-28 18:46 UTC, fanatiicx commented
@prokopsimek Good note about the plurality! I will make some edits to improve the article over the next week or two :)

2021-06-28 18:47 UTC, prokopsimek commented
@fanatiicx It will be awesome! Thanks and let me know if you need any help. :)

2021-07-21 09:01 UTC, prokopsimek commented
@fanatiicx Hello! How're you doing? Can I help you finish the article? 🙂

2021-07-21 13:45 UTC, fanatiicx commented
@prokopsimek I would greatly appreciate it! It'd be a great way to learn from your edits.

I was not feeling well last week and will be travelling next week, hence I've been a bit slow with editing this piece. Thanks for your patience :)

2021-07-30 22:12 UTC, fanatiicx reviewed
I'm back from vacation and made the suggested changes. I would be happy to hear your feedback. Thanks!

2021-08-03 05:37 UTC, prokopsimek commented
@fanatiicx Great job! Thank you for completing your PR. Awesome! 👏 😎

2021-08-03 05:38 UTC, prokopsimek approved these changes

2021-08-03 05:38 UTC, merged

2021-08-03 05:49 UTC, prokopsimek commented
@fanatiicx https://developerexperience.io/practices/test-cards Thank you!
I have to fix contributors loading.

2021-08-03 14:57 UTC, fanatiicx commented
@prokopsimek Thanks! 

By the way, I noticed a typo in the last section. Wasn't sure where to edit so I opened a [pull request](https://github.com/DXHeroes/knowledge-base-content/pull/373) for it with the changes made.

2021-08-03 15:00 UTC, prokopsimek commented
@fanatiicx  Fixed, thanks!